
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Models;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int function = 2;
  public static final int parametro_entada_salida = 11;
  public static final int parametro_entrada = 9;
  public static final int suma = 22;
  public static final int resta = 23;
  public static final int down_to = 47;
  public static final int imprimir = 59;
  public static final int comparacion = 29;
  public static final int hasta = 45;
  public static final int coma = 44;
  public static final int corchete_cerrado = 43;
  public static final int parentesis_cerrado = 39;
  public static final int letra = 49;
  public static final int boolean_type = 4;
  public static final int multiplicacion = 24;
  public static final int ciclo_repeat = 14;
  public static final int comilla_abierta = 53;
  public static final int llave_cerrada = 41;
  public static final int dos_puntos = 56;
  public static final int int_type = 5;
  public static final int char_type = 7;
  public static final int end_for = 55;
  public static final int numero = 51;
  public static final int then = 18;
  public static final int menor = 27;
  public static final int EOF = 0;
  public static final int mayor_igual = 31;
  public static final int error = 1;
  public static final int string_type = 8;
  public static final int mayor = 28;
  public static final int end_while = 57;
  public static final int entero = 50;
  public static final int corchete_abierto = 42;
  public static final int or = 34;
  public static final int parentesis_abierto = 38;
  public static final int procedure = 3;
  public static final int ciclo_while = 13;
  public static final int menor_igual = 30;
  public static final int condicional_if = 15;
  public static final int id = 52;
  public static final int condicional_switch = 16;
  public static final int potencia = 26;
  public static final int llave_abierta = 40;
  public static final int caso = 21;
  public static final int hacer = 46;
  public static final int end_if = 20;
  public static final int ciclo_for = 12;
  public static final int diferente = 33;
  public static final int not = 36;
  public static final int and = 35;
  public static final int condicional_until = 17;
  public static final int parametro_salida = 10;
  public static final int lambda = 58;
  public static final int comilla_cerrada = 54;
  public static final int asignacion = 37;
  public static final int division = 25;
  public static final int decimal = 60;
  public static final int modulo = 32;
  public static final int digito = 48;
  public static final int float_type = 6;
  public static final int sino = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "function",
  "procedure",
  "boolean_type",
  "int_type",
  "float_type",
  "char_type",
  "string_type",
  "parametro_entrada",
  "parametro_salida",
  "parametro_entada_salida",
  "ciclo_for",
  "ciclo_while",
  "ciclo_repeat",
  "condicional_if",
  "condicional_switch",
  "condicional_until",
  "then",
  "sino",
  "end_if",
  "caso",
  "suma",
  "resta",
  "multiplicacion",
  "division",
  "potencia",
  "menor",
  "mayor",
  "comparacion",
  "menor_igual",
  "mayor_igual",
  "modulo",
  "diferente",
  "or",
  "and",
  "not",
  "asignacion",
  "parentesis_abierto",
  "parentesis_cerrado",
  "llave_abierta",
  "llave_cerrada",
  "corchete_abierto",
  "corchete_cerrado",
  "coma",
  "hasta",
  "hacer",
  "down_to",
  "digito",
  "letra",
  "entero",
  "numero",
  "id",
  "comilla_abierta",
  "comilla_cerrada",
  "end_for",
  "dos_puntos",
  "end_while",
  "lambda",
  "imprimir",
  "decimal"
  };
}

