
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Models;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int menorigual = 22;
  public static final int verdad = 17;
  public static final int t_boolean = 12;
  public static final int seleccionar = 24;
  public static final int numero = 31;
  public static final int t_cadena = 11;
  public static final int punto = 26;
  public static final int menor = 19;
  public static final int t_numeric = 13;
  public static final int insertar = 8;
  public static final int parentesiscierra = 5;
  public static final int set = 15;
  public static final int digito = 29;
  public static final int mayorigual = 21;
  public static final int igual = 23;
  public static final int EOF = 0;
  public static final int herencia = 7;
  public static final int letra = 30;
  public static final int id = 33;
  public static final int automatico = 3;
  public static final int re = 27;
  public static final int from = 25;
  public static final int error = 1;
  public static final int t_date = 14;
  public static final int entero = 32;
  public static final int asterisco = 28;
  public static final int valores = 9;
  public static final int parentesisabre = 4;
  public static final int composicion = 10;
  public static final int get = 16;
  public static final int falso = 18;
  public static final int puntoycoma = 6;
  public static final int object = 2;
  public static final int mayor = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "object",
  "automatico",
  "parentesisabre",
  "parentesiscierra",
  "puntoycoma",
  "herencia",
  "insertar",
  "valores",
  "composicion",
  "t_cadena",
  "t_boolean",
  "t_numeric",
  "t_date",
  "set",
  "get",
  "verdad",
  "falso",
  "menor",
  "mayor",
  "mayorigual",
  "menorigual",
  "igual",
  "seleccionar",
  "from",
  "punto",
  "re",
  "asterisco",
  "digito",
  "letra",
  "numero",
  "entero",
  "id"
  };
}

